default: &default
  host: <%= ENV.fetch("DATABASE_HOST") { "localhost" } %>
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: mk_1_dev
  username: postgres
  password:

test:
  <<: *default
  database: mk_1_test
  username: postgres
  password:

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>